name: flutter_my
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^2.2.1
  cupertino_icons: ^0.1.2
  path_provider: ^0.5.0
  shared_preferences: ^0.4.1
  pie_chart: ^3.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
   - image/penguin1.png